name: "Publish: NPM"

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Get version from package.json
        id: package_version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ steps.package_version.outputs.current-version }}
          release_name: ${{ steps.package_version.outputs.current-version }}
          body: ${{ steps.package_version.outputs.current-version }}
          draft: false
          prerelease: false

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}